Fix finding the target global container
ivnvxd/arc-export pull request #11
Opened 2024-09-21 00:04 UTC by AlpyneDreams

The code submitted in PR #5 will always give an index of 1 which is wrong and gave no bookmarks when I ran the script. This PR fixes that bug.

2024-09-24 21:48 UTC, ivnvxd reviewed
If no container with "global" is found, this will raise a `StopIteration` exception. It might be worth considering adding a fallback or error handling for this case.

```python
try:
    target: int = next(i + 1 for i, c in enumerate(containers) if "global" in c)
except StopIteration:
    raise ValueError("No container with 'global' found in the sidebar data")
```
Or something like that.

2024-09-28 09:41 UTC, chenasraf commented
This fixed the issue for me, thanks :)

2024-10-05 17:34 UTC, ivnvxd requested changes

2024-10-05 17:34 UTC, ivnvxd commented on main.py
> +    target: int = next(i + 1 for i, c in enumerate(containers) if "global" in c)
If no container with "global" is found, this will raise a StopIteration exception. It might be worth considering adding a fallback or error handling for this case.
```suggestion
    try:
        target: int = next(i + 1 for i, c in enumerate(containers) if "global" in c)
    except StopIteration:
        raise ValueError("No container with 'global' found in the sidebar data")
```

2024-12-15 23:05 UTC, ivnvxd approved these changes

2024-12-15 23:05 UTC, merged